import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'
import type { UiLocale } from '../../shared/protocol'

export type LanguagePreference = 'system' | UiLocale

type TranslationValues = Record<string, string | number>

const zhCN: Record<string, string> = {
  'File': '文件',
  'Edit': '编辑',
  'View': '视图',
  'Language': '语言',
  'Debug': '调试',
  'Window': '窗口',
  'Help': '帮助',
  'Open...': '打开...',
  'Save As...': '另存为...',
  'Save Code...': '保存代码...',
  'Close All Tabs': '关闭所有标签页',
  'Close All But This': '除此之外全部关闭',
  'New Tab': '新标签页',
  'New Horizontal Tab Group': '新建水平标签组',
  'New Vertical Tab Group': '新建垂直标签组',
  'Tab actions': '标签页操作',
  'Close Workspace': '关闭工作区',
  'Exit': '退出',
  'Undo': '撤销',
  'Redo': '重做',
  'Find': '查找',
  'Rename...': '重命名...',
  'Edit IL Body...': '编辑 IL 方法体...',
  'Replace Resource...': '替换资源...',
  'Blue Theme': '蓝色主题',
  'Light Theme': '浅色主题',
  'Dark Theme': '深色主题',
  'High Contrast': '高对比度',
  'Blue': '蓝色',
  'Dark': '深色',
  'Light': '浅色',
  'Word Wrap': '自动换行',
  'Highlight Current Line': '高亮当前行',
  'Full Screen': '全屏',
  'Collapse Tree View Nodes': '折叠树状图节点',
  'Code': '代码',
  'Hex View': '十六进制视图',
  'Hex': '十六进制',
  'Info': '信息',
  'Module Information': '模块信息',
  'System Default': '跟随系统',
  'English': 'English',
  'Simplified Chinese': '简体中文',
  'Continue': '继续',
  'Start Debugging': '开始调试',
  'Start Debugging...': '开始调试...',
  'Debug a Program': '调试程序',
  'Debug Program': '调试程序',
  'Executable': '可执行程序',
  'Arguments': '调试参数',
  'Working Directory': '工作目录',
  // The Debug Program dialog's environment box; "Environment" alone already names an Options category.
  'Environment Variables': '环境变量',
  'Break at': '中断于',
  "Don't Break": '不要中断',
  'Entry Point': '入口点',
  'Browse...': '浏览...',
  'One KEY=VALUE per line': '每行一个 KEY=VALUE',
  'OK': '确定',
  'Attach to Process...': '附加到进程...',
  'Pause': '暂停',
  'Step Into': '逐语句',
  'Step Over': '逐过程',
  'Step Out': '跳出',
  'Stop Debugging': '停止调试',
  'Stop': '停止',
  'Options...': '选项...',
  'Restore Defaults': '恢复默认值',
  'Assembly Explorer': '程序集资源管理器',
  'Output': '输出',
  'Search': '搜索',
  'Analyzer': '分析器',
  'Locals': '局部变量',
  'Watch': '监视',
  'Call Stack': '调用堆栈',
  'Breakpoints': '断点',
  'Module Breakpoints': '模块断点',
  'Exception Settings': '异常设置',
  'Threads': '线程',
  'Modules': '模块',
  'Autos': '自动变量',
  'Static Fields': '静态字段',
  'Processes': '进程',
  'Memory': '内存',
  'Disassembly': '反汇编',
  'Start': '开始',
  'Latest Release': '最新发布版本',
  'Report Bug': '上报错误',
  'Source Code': '源代码',
  'About dnSpy': '关于 dnSpy',
  'Workspace': '工作区',
  'Open Assembly': '打开程序集',
  'Save As': '另存为',
  'Back': '后退',
  'Forward': '前进',
  'Working': '正在处理',
  'Ready': '就绪',
  'Modified': '已修改',
  'Dismiss': '关闭提示',
  'Loading': '正在加载',
  'No assemblies loaded': '未加载程序集',
  'Collapse': '折叠',
  'Expand': '展开',
  'Main toolbar': '主工具栏',
  'Window controls': '窗口控件',
  'Minimize window': '最小化窗口',
  'Maximize window': '最大化窗口',
  'Restore window': '还原窗口',
  'Minimize': '最小化',
  'Maximize': '最大化',
  'Restore': '还原',
  'Close window': '关闭窗口',
  'Close': '关闭',
  'Search assemblies': '搜索程序集',
  'Document closed': '文档已关闭',
  'Decompiler language': '反编译语言',
  'Definition': '定义',
  'Go to definition (F12)': '转到定义 (F12)',
  'Enabled': '已启用',
  'Disabled': '已禁用',
  'Previous page': '上一页',
  'Next page': '下一页',
  'Offset': '偏移',
  'Name': '名称',
  'Value': '值',
  'Type': '类型',
  'Path': '路径',
  'Runtime': '运行时',
  'Architecture': '架构',
  'Kind': '类型',
  'Entry point': '入口点',
  'Types': '类型',
  'Resources': '资源',
  'Base type': '基类型',
  'Instruction': '指令',
  'None': '无',
  'Assembly References': '程序集引用',
  'PE Headers': 'PE 头',
  'Metadata Tables': '元数据表',
  'Table': '表',
  'Rows': '行数',
  'Expression': '表达式',
  'Symbols': '符号',
  'Watch expression': '监视表达式',
  'Add watch': '添加监视',
  'Function breakpoint': '函数断点',
  'Add function breakpoint': '添加函数断点',
  'Toggle Breakpoint': '切换断点',
  'Toggle Method Breakpoint': '切换方法断点',
  'Delete All Breakpoints': '删除所有断点',
  'Bound': '已绑定',
  'Module not loaded yet.': '模块尚未加载。',
  'Not supported by this debug engine': '当前调试引擎不支持',
  'Enable All Breakpoints': '启用所有断点',
  'Disable All Breakpoints': '禁用所有断点',
  'Do you want to delete all breakpoints?': '是否删除所有的断点？',
  'Enable {name}': '启用 {name}',
  'Disable {name}': '禁用 {name}',
  'All thrown exceptions': '所有抛出的异常',
  'User-unhandled exceptions': '用户未处理的异常',
  'Attach to Process': '附加到进程',
  'Filter processes': '筛选进程',
  'Filter': '筛选',
  'Refresh': '刷新',
  'Cancel': '取消',
  'Attach': '附加',
  'Rename': '重命名',
  'Edit IL · {name}': '编辑 IL · {name}',
  'Max stack': '最大堆栈',
  'Initialize locals': '初始化局部变量',
  'Clear exception handlers': '清除异常处理程序',
  'Label': '标签',
  'Opcode': '操作码',
  'Operand': '操作数',
  'Number': '数字',
  'String': '字符串',
  'Branch': '分支',
  'Switch': '切换',
  'Local': '局部变量',
  'Argument': '参数',
  'Token': '令牌',
  'Add': '添加',
  'Apply': '应用',
  'Close About': '关闭“关于”对话框',
  'Version 1.0.0': '版本 1.0.0',
  'Cross-platform .NET assembly browser, decompiler, editor and debugger.': '跨平台 .NET 程序集浏览器、反编译器、编辑器和调试器。',
  'Licensed under GNU GPL v3.0 only.': '仅依 GNU GPL v3.0 许可证授权。',
  'Discard unsaved changes and close the workspace?': '放弃未保存的更改并关闭工作区吗？',
  'Stopped: {reason}': '已停止：{reason}',
  'starting': '正在启动',
  'ready': '就绪',
  'running': '正在运行',
  'stopped': '已停止',
  'inactive': '未启动',
  'error': '错误',
  'unknown': '未知',
  'breakpoint': '断点',
  'function breakpoint': '函数断点',
  'data breakpoint': '数据断点',
  'instruction breakpoint': '指令断点',
  'entry': '入口点',
  'step': '单步',
  'pause': '用户暂停',
  'exception': '异常',
  'Remove {name}': '移除 {name}',
  'Collapse {name}': '折叠 {name}',
  'Expand {name}': '展开 {name}',
  'Label {index}': '标签 {index}',
  'Opcode {index}': '操作码 {index}',
  'Operand kind {index}': '操作数类型 {index}',
  'Operand {index}': '操作数 {index}',
  'Delete instruction': '删除指令',
  'Delete instruction {index}': '删除指令 {index}',
  'Navigation failed: {message}': '导航失败：{message}',
  'Backend: {state}': '后端：{state}',
  'Backend: {state} - {message}': '后端：{state} - {message}',
  'Opened {count} module(s).': '已打开 {count} 个模块。',
  'Open failed: {message}': '打开失败：{message}',
  'Workspace closed.': '工作区已关闭。',
  'Tree load failed: {message}': '加载树失败：{message}',
  'No workspace is open.': '没有打开的工作区。',
  'Decompile failed: {message}': '反编译失败：{message}',
  'Search returned {count} result(s).': '搜索返回 {count} 个结果。',
  'Search failed: {message}': '搜索失败：{message}',
  'Analysis returned {count} reference(s).': '分析返回 {count} 个引用。',
  'Analysis failed: {message}': '分析失败：{message}',
  'Renamed {oldName} to {newName}.': '已将 {oldName} 重命名为 {newName}。',
  'Rename failed: {message}': '重命名失败：{message}',
  'Replaced resource {name}.': '已替换资源 {name}。',
  'Resource replacement failed: {message}': '替换资源失败：{message}',
  'Saved {path} ({length} bytes, SHA-256 {sha256}).': '已保存 {path}（{length} 字节，SHA-256 {sha256}）。',
  'Save failed: {message}': '保存失败：{message}',
  'Saved code to {path}.': '代码已保存到 {path}。',
  'Save code failed: {message}': '保存代码失败：{message}',
  'Updated IL body for {name}.': '已更新 {name} 的 IL 方法体。',
  'Undo completed.': '撤销完成。',
  'Undo failed: {message}': '撤销失败：{message}',
  'Redo completed.': '重做完成。',
  'Redo failed: {message}': '重做失败：{message}',
  'Started debugging {target}.': '已开始调试 {target}。',
  'Debug launch failed: {message}': '启动调试失败：{message}',
  'Attached to process {processId}.': '已附加到进程 {processId}。',
  'Debug attach failed: {message}': '附加调试失败：{message}',
  'Debugger stopped: {reason}.': '调试器已停止：{reason}。',
  'Debug target exited with code {code}.': '调试目标已退出，代码为 {code}。',
  'Debug session terminated.': '调试会话已终止。',
  'Could not refresh debugger state: {message}': '无法刷新调试器状态：{message}',
  'IL edit failed: {message}': 'IL 编辑失败：{message}',
  'Close tab': '关闭选项卡',
  'Pinned': '已固定',
  'Rename tab': '重命名选项卡',
  'Close tabset': '关闭选项卡组',
  'Active tabset': '活动选项卡组',
  'Move tabset': '移动选项卡组',
  'Move tabs (?)': '移动选项卡 (?)',
  'Move group (?)': '移动组 (?)',
  'Maximize tabset': '最大化选项卡组',
  'Restore tabset': '还原选项卡组',
  'Popout selected tab': '在新窗口中打开所选选项卡',
  'Float selected tab': '浮动所选选项卡',
  'Popout panel': '在新窗口中打开面板',
  'Drag into another layout': '拖入其他布局',
  'Dock tabs (?)': '停靠选项卡 (?)',
  'Hidden tabs': '隐藏的选项卡',
  'Resize': '调整大小',
  'Error rendering component': '组件渲染失败',
  'Retry': '重试',
  'Popout Window': '弹出窗口',
  'Pin': '固定',
  'Unpin': '取消固定',
  'Popout': '弹出',
  'Float': '浮动',
  'Pop out tabset': '弹出选项卡组',
  'Float tabset': '浮动选项卡组',
  'Overlay': '覆盖',
  'Split': '拆分',
  'Close All': '全部关闭',
  'Close to the Right': '关闭右侧选项卡',
  'Close Others': '关闭其他选项卡',
  'Add to new group': '添加到新组',
  'Add to group': '添加到组',
  'Remove from group': '从组中移除',
  'Ungroup': '取消分组',
  'Rename group': '重命名组',
  'Group color': '组颜色',
  'Tab Group, click to expand/collapse': '选项卡组，单击展开或折叠',
  'Group Name': '组名称',
  'Group color ?': '组颜色 ?',
  'Group': '组',
  'Options': '选项',
  'Prevent code from detecting the debugger': '防止代码检测调试器',
  'Enable property evaluation and other implicit function calls': '启用属性求值和其它隐式函数调用',
  'Call string-conversion function on objects in variables windows': '在变量窗口中对对象调用字符串转换方法',
  'Step over properties and operators': '逐过程执行属性和运算符',
  'Ignore Debugger.Break() and break instructions': '忽略 Debugger.Break() 和中断指令',
  'Show the Locals window when the debugger starts': '在调试器启动时显示局部变量窗口',
  'Debug files loaded from the process\' memory (uncheck to use disk files)': '调试从进程内存加载的文件 (取消选中以使用磁盘文件)',
  'Break all processes when one process breaks': '一个进程中断时则中断所有进程',
  'Enable async debugging': '启用异步调试',
  'Give focus to debugged process': '使被调试进程获得焦点',
  'Bring dnSpy to the foreground when breaking in the debugger': '当调试器中断时，为 dnSpy 设置焦点',
  'Redirect GUI applications\' console output to the Output window': '将 GUI 应用程序的控制台输出重定向到 "输出" 窗口',
  'Enable Managed Debugging Assistants (MDA)': '启用托管调试助手 (MDA)',
  'Enable Just My Code debugging support': '启用"仅我的代码"',
  'Step over code in system modules': '跳过系统模块中的代码(系统自带程序集)',
  'Only step into code located in primary module': '仅进入主模块中的代码',
  'Show raw structure of objects in variables windows': '在变量窗口中显示对象的原始结构',
  'Ignore unhandled exceptions': '忽略未处理的异常',
  'Suppress JIT optimization on module load': '在模块加载时禁用 JIT 优化',
  'System modules': '系统模块',
  'Program modules': '程序模块',
  'Hide compiler generated members': '隐藏编译器生成的成员',
  'Respect attributes that hide members': '遵守隐藏成员的特性',
  'Hide deprecated members in variables windows': '在变量窗口中隐藏已弃用的成员',
  'Sort parameters': '对参数排序',
  'Sort locals': '对局部变量排序',
  'Group parameters and locals together': '组合参数和局部变量',
  'Show compiler generated variables': '显示编译器生成的变量',
  'Show decompiler generated variables': '显示反编译器生成的变量',
  'Show raw locals': '显示原始区域变量',
  'Show return values': '显示返回值',
  'Highlight changed variables in variables windows': '在变量窗口中高亮显示更改过的变量',
  'Syntax highlight': '语法高亮',
  'Debug Engine': '调试引擎',
  'Debugger': '调试器',
  'Environment': '环境',
  'Decompiler': '反编译器',
  'Categories': '分类',
  'Search settings': '搜索设置',
  'Clear search': '清除搜索',
  'No categories match your search.': '没有符合搜索条件的分类。',
  'Select a category to view its settings.': '请选择一个分类以查看其设置。',
  'Settings shared by every debugger engine that the cross-platform backend supports.': '由跨平台后端支持的所有调试器引擎共享的设置。',
  'Cross-cutting settings that affect every part of the app.': '影响应用各个部分的全局设置。',
  'Settings that influence how .NET assemblies are decompiled into source code.': '影响 .NET 程序集如何被反编译为源代码的设置。',

  // Compiler, Disassembler, Text Viewer, Code Editor, REPL, Output, Assembly Explorer,
  // BAML, Hex Editor, Background Image and Bookmarks settings pages.
  'Compiler': '编译器',
  'Disassembler': '反汇编器',
  'Text Viewer': '文本查看器',
  'Code Editor': '代码编辑器',
  'Output Window': '输出窗口',
  'Hex Editor': '十六进制编辑器',
  'Background Image': '背景图像',
  'Bookmarks': '书签',
  'Code Style': '代码样式',
  'Default': '默认',
  'Memory Window': '内存窗口',
  'General': '常规',
  'Scroll Bars': '滚动条',
  'Tabs': '制表符',
  'Advanced': '高级',
  'Appearance': '外观',
  'Line height': '行高',
  'Margins': '边距',
  'Zoom': '缩放',
  'Order (restart needed)': '顺序 (需要重启)',

  'Virtual space': '虚拟空间',
  'Word wrap': '自动换行',
  'Line numbers': '行号',
  'Highlight current line': '高亮当前行',
  'Highlight the current line': '高亮当前行',
  'Show line numbers': '显示行号',
  'Syntax highlight source documents': '对源文档进行语法高亮',
  'Show the minimap': '显示缩略图',
  'Show horizontal scroll bar': '显示水平滚动条',
  'Show vertical scroll bar': '显示垂直滚动条',
  'Tab size': '制表符大小',
  'Indent size': '缩进大小',
  'Convert tabs to spaces': '将制表符转换为空格',
  'Show timestamps': '显示时间戳',
  'Timestamp format': '时间戳格式',
  'Highlight references': '高亮引用',
  'Highlight related keywords': '高亮相关关键字',
  'Highlight braces': '高亮括号',
  'Show procedure line separators': '显示过程分隔线',
  'Show indent guides': '显示缩进参考线',
  'Indent guides style': '缩进参考线样式',
  'Solid lines': '实线',
  'Dashed lines (1px)': '虚线 (1px)',
  'Dashed lines (2px)': '虚线 (2px)',
  'Dashed lines (3px)': '虚线 (3px)',
  'Dashed lines (4px)': '虚线 (4px)',
  'Compress blank lines': '压缩空行',
  'Compress lines that do not have any alphanumeric characters': '压缩不含任何字母数字字符的行',
  "Don't add extra line spacing": '不添加额外的行距',
  'Selection margin': '选定内容边距',
  'Indicator margin': '指示器边距',
  'Mouse wheel zoom': '鼠标滚轮缩放',
  'Zoom control': '缩放控件',

  'Syntax': '语法',
  'Show disassembly in a new tab': '在新标签页中显示反汇编',
  'Show instruction address': '显示指令地址',
  'Show instruction bytes': '显示指令字节',
  'Show IL code': '显示 IL 代码',
  'Show decompiled code': '显示反编译的代码',
  'Add an empty line between blocks': '在块之间添加空行',
  'Add labels': '添加标签',
  'Upper case prefixes': '前缀大写',
  'Upper case mnemonics': '助记符大写',
  'Upper case registers': '寄存器大写',
  'Upper case keywords': '关键字大写',
  'Upper case hex numbers': '十六进制数字大写',
  'Upper case everything': '全部大写',
  'Space after operand separator': '操作数分隔符后的空格',
  'Space after memory operand brackets': '内存操作数方括号后的空格',
  "Space between '+'": "'+' 之间的空格",
  "Space between '*'": "'*' 之间的空格",
  'Show scale before index register': '在索引寄存器之前显示比例',
  'Always show the scale value': '始终显示比例值',
  'Always show segment registers': '始终显示段寄存器',
  'Show zero displacements': '显示零位移',
  'Add leading zeroes': '添加前导零',
  'Add leading zeroes (branches)': '添加前导零 (分支)',
  'Show small numbers in decimal': '以十进制显示小数字',
  "Add leading '0' to hex numbers if needed": '根据需要为十六进制数字添加前导 "0"',
  'Signed numbers': '有符号数字',
  'Signed displacements': '有符号位移',
  'Always show size of memory operands': '始终显示内存操作数的大小',
  'RIP-relative addresses': 'RIP 相对地址',
  'Show branch size': '显示分支大小',
  'Pseudo instructions': '伪指令',
  'Show symbol address': '显示符号地址',
  'Hex numbers': '十六进制数字',
  'Space after memory operand comma': '内存操作数逗号后的空格',
  'Naked registers': '裸寄存器',
  'Always show mnemonic size suffix': '始终显示助记符大小后缀',
  'Operand column': '操作数列',
  'Hex prefix': '十六进制前缀',
  'Hex suffix': '十六进制后缀',
  'Digit separator': '数字分隔符',

  'Conditional compilation symbols': '条件编译符号',
  'Optimize code': '优化代码',
  'Check for arithmetic overflow/underflow': '检查算术溢出/下溢',
  'Allow unsafe code': '允许不安全代码',
  'Option explicit': 'Option Explicit',
  'Option infer': 'Option Infer',
  'Option strict': 'Option Strict',
  'Option compare: binary': 'Option Compare: Binary',
  'Embed Visual Basic runtime': '嵌入 Visual Basic 运行时',

  'Dragged items filter': '拖放项筛选器',
  'All': '全部',
  'All supported': '所有支持的项',
  '.NET only': '仅 .NET',
  'Show metadata tokens': '显示元数据令牌',
  'Show assembly version': '显示程序集版本',
  'Show assembly public key token': '显示程序集公钥令牌',
  'Single-click expands nodes': '单击展开节点',
  'Nested Types': '嵌套类型',
  'Fields': '字段',
  'Events': '事件',
  'Properties': '属性',
  'Methods': '方法',

  'One attribute per line': '每行一个特性',
  'Use tabs': '使用制表符',
  'Disassemble BAML': '反汇编 BAML',

  'Highlight current value': '高亮当前值',
  'Highlight structure under mouse cursor': '高亮鼠标光标下的结构',
  'Lower case hex (values)': '十六进制小写 (值)',
  'Lower case hex (offset)': '十六进制小写 (偏移)',
  'Colorize the text': '为文本着色',
  'Group size': '组大小',
  'Encoding': '编码',
  'UTF-16 (Big Endian)': 'UTF-16 (大端序)',
  'Western European (ISO)': '西欧 (ISO)',
  'Show column line separators': '显示列分隔线',

  'Add paths to images and image folders, one path per line:': '添加图像和图像文件夹的路径，每行一个路径：',
  'Placement': '位置',
  'Top Left': '左上',
  'Top Right': '右上',
  'Bottom Left': '左下',
  'Bottom Right': '右下',
  'Top': '上',
  'Left': '左',
  'Right': '右',
  'Bottom': '下',
  'Center': '居中',
  'Opacity': '不透明度',
  'Stretch': '拉伸',
  'Fill': '填充',
  'Uniform': '均匀',
  'UniformToFill': '均匀填充',
  'Direction': '方向',
  'Both': '双向',
  'Up Only': '仅放大',
  'Down Only': '仅缩小',
  'Interval': '间隔',
  'Zoom %': '缩放 %',
  'Random Image': '随机图像',
  'Show Images': '显示图像',
  'Horizontal Offset': '水平偏移',
  'Vertical Offset': '垂直偏移',
  'Left Margin %': '左边距 %',
  'Right Margin %': '右边距 %',
  'Top Margin %': '上边距 %',
  'Bottom Margin %': '下边距 %',
  'Max Width': '最大宽度',
  'Max Height': '最大高度',

  'Theme': '主题',


  'App-wide behaviour such as the colour theme, restart handling and update checks.': '包括色彩主题、重启处理与更新检查等全局行为。',
  'The font and size used by the text editor.': '文本编辑器使用的字体和字号。',
  'Font': '字体',
  'Size': '大小',
  'Allow more than one instance (restart required)': '允许多个实例 (需要重启)',
  "Decompile a member's enclosing class instead of the class member": '反编译成员所在的类，而不是该成员',
  'Restore tabs at startup': '启动时还原标签页',
  'Use memory mapped I/O': '使用内存映射 I/O',
  'Check for updates on startup': '启动时检查更新',
  'Decompilation order': '反编译顺序',
  'Decompile anonymous methods/lambdas': '反编译匿名方法/Lambda',
  'Decompile enumerators (yield return)': '反编译枚举器 (yield return)',
  'Decompile async methods (async/await)': '反编译异步方法 (async/await)',
  'Decompile query expressions': '反编译查询表达式',
  'Decompile expression trees': '反编译表达式树',
  'Use variable names from debug symbols, if available': '使用调试符号中的变量名 (如果有)',
  'Add namespaces to all types': '为所有类型添加命名空间',
  'Add a namespace to types with the same name': '为同名的类型添加命名空间',
  'Show XML documentation in decompiled code': '在反编译的代码中显示 XML 文档',
  'Remove empty default constructors': '移除空的默认构造函数',
  'Show tokens, RVAs and file offsets': '显示令牌、RVA 和文件偏移',
  'Sort methods, fields, properties, events and types': '对方法、字段、属性、事件和类型排序',
  'Show hidden compiler generated types and methods': '显示隐藏的编译器生成的类型和方法',
  "Place 'System' directives first when sorting usings": '排序 using 时优先放置 "System" 指令',
  'Sort custom attributes': '对自定义特性排序',
  'Order members in source code order': '按源代码顺序排列成员',
  'Show one custom attribute per line': '每行显示一个自定义特性',
  'Allow field initializers': '允许字段初始值设定项',
  "Add 'internal' modifier to types": '为类型添加 "internal" 修饰符',
  "Add 'private' modifier to type members": '为类型成员添加 "private" 修饰符',
  'Hexadecimal numbers': '十六进制数字',
  'Decompile calli to invocation expression': '将 calli 反编译为调用表达式',
  'Insert parentheses for readability': '为便于阅读插入括号',
  'Show IL instruction bytes': '显示 IL 指令字节',
  'Show IL opcode comments': '显示 IL 操作码注释',
  'Show line numbers and filenames if available': '显示行号和文件名 (如果有)',
}

function resolveSystemLocale(): UiLocale {
  const locales = typeof navigator === 'undefined' ? [] : navigator.languages?.length ? navigator.languages : [navigator.language]
  return locales.some((locale) => locale.toLowerCase().startsWith('zh')) ? 'zh-CN' : 'en'
}

let activeLocale: UiLocale = resolveSystemLocale()

const resolveLocale = (language: LanguagePreference): UiLocale => language === 'system' ? resolveSystemLocale() : language

export const translate = (message: string, values: TranslationValues = {}): string => {
  const template = activeLocale === 'zh-CN' ? zhCN[message] ?? message : message
  return template.replace(/\{(\w+)\}/g, (placeholder, name: string) => String(values[name] ?? placeholder))
}

export const getActiveLocale = (): UiLocale => activeLocale

const loadLanguage = (): LanguagePreference => {
  const saved = localStorage.getItem('dnspy.language')
  return saved === 'en' || saved === 'zh-CN' || saved === 'system' ? saved : 'system'
}

interface LanguageContextValue {
  language: LanguagePreference
  locale: UiLocale
  setLanguage(language: LanguagePreference): void
  t: typeof translate
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'system',
  locale: activeLocale,
  setLanguage: () => undefined,
  t: translate,
})

export const LanguageProvider = ({ children, initialLanguage }: React.PropsWithChildren<{ initialLanguage?: LanguagePreference }>): React.JSX.Element => {
  const [language, setLanguageState] = useState<LanguagePreference>(() => initialLanguage ?? loadLanguage())
  const locale = resolveLocale(language)
  activeLocale = locale

  useEffect(() => {
    document.documentElement.lang = locale
    document.documentElement.dataset.locale = locale
    if (initialLanguage === undefined)
      localStorage.setItem('dnspy.language', language)
    void window.dnSpy?.setLocale?.(locale)
  }, [initialLanguage, language, locale])

  const setLanguage = useCallback((nextLanguage: LanguagePreference) => setLanguageState(nextLanguage), [])
  const context = useMemo<LanguageContextValue>(() => ({ language, locale, setLanguage, t: translate }), [language, locale, setLanguage])
  return <LanguageContext.Provider value={context}>{children}</LanguageContext.Provider>
}

export const useLanguage = (): LanguageContextValue => useContext(LanguageContext)
