import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'
import type { UiLocale } from '../../shared/protocol'

export type LanguagePreference = 'system' | UiLocale

export type TranslationValues = Record<string, string | number>

const zhCN: Record<string, string> = {
  'File': '文件',
  'Edit': '编辑',
  'View': '视图',
  'Language': '语言',
  'Debug': '调试',
  'Window': '窗口',
  'Help': '帮助',
  'Open...': '打开...',
  'Save As...': '另存为...',
  'Save Code...': '保存代码...',
  'Close All Tabs': '关闭所有标签页',
  'Close All But This': '除此之外全部关闭',
  'New Tab': '新标签页',
  'New Horizontal Tab Group': '新建水平标签组',
  'New Vertical Tab Group': '新建垂直标签组',
  'Tab actions': '标签页操作',
  'Close Workspace': '关闭工作区',
  'Exit': '退出',
  'Undo': '撤销',
  'Redo': '重做',
  'Find': '查找',
  // dnSpy's Edit menu (dnSpy.Resources.zh-CN.resx / dnSpy.AsmEditor.Resources.zh-CN.resx). Entries the
  // port has not implemented yet are still listed and translated — they render disabled.
  'Search Assemblies': '搜索程序集',
  'Find String References in Module': '查找模块中的全部字符串',
  'Remove {name}': '移除 {name}',
  'Remove NetModule from Assembly': '从程序集中移除 NetModule',
  'Delete {name}': '删除 {name}',
  'Delete Namespace': '删除命名空间',
  'Move Types to Empty Namespace': '将类型移动到空命名空间下',
  'Rename Namespace': '重命名命名空间',
  'Convert NetModule to Assembly': '转换模块为程序集',
  'Convert Assembly to NetModule': '转换程序集为模块',
  'Create Assembly...': '创建程序集...',
  'Add New NetModule to Assembly...': '添加新的模块到程序集...',
  'Add Existing NetModule to Assembly...': '添加现有模块到程序集...',
  'Create NetModule...': '创建模块...',
  'Create Type...': '创建类型...',
  'Create Nested Type...': '创建嵌套的类型...',
  'Create Method...': '创建方法...',
  'Create Field...': '创建字段...',
  'Create Property...': '创建属性...',
  'Create Event...': '创建事件...',
  'Create File Resource...': '创建文件资源...',
  'Create Multi File Resource...': '创建多文件资源...',
  'Create Assembly Linked Resource...': '创建程序集链接资源...',
  'Create File Linked Resource...': '创建链接文件资源...',
  'Create System.Data.Bitmap/Icon Resource...': '创建 System.Data.Bitmap/Icon 资源...',
  'Create System.Windows.Forms.ImageListStreamer Resource...': '创建 System.Windows.Forms.ImageListStreamer 资源...',
  'Create Byte Array Resource...': '创建字节数组资源...',
  'Create System.IO.Stream Resource...': '创建 System.IO.Stream 资源...',
  'Create Resource...': '创建资源...',
  'Edit Assembly...': '编辑程序集...',
  'Edit Module...': '编辑模块...',
  'Edit Type...': '编辑类型...',
  'Edit Method...': '编辑方法...',
  'Edit Method ({language})...': '编辑方法 ({language})...',
  'Edit Assembly Attributes ({language})...': '编辑程序集特性 ({language})...',
  'Edit Class ({language})...': '编辑类 ({language})...',
  'Add Class Members ({language})...': '添加类成员 ({language})...',
  'Add Class ({language})...': '添加类 ({language})...',
  'Merge with Assembly...': '与程序集合并...',
  'Edit Field...': '编辑字段...',
  'Edit Method Body...': '编辑方法体...',
  'Replace Method Body with stub...': '将方法体替换为存根...',
  'Load Dependencies': '加载依赖',
  'Load Dependencies Recursively': '加载所有依赖',
  'Edit Property...': '编辑属性...',
  'Edit Event...': '编辑事件...',
  'Edit Resource...': '编辑资源...',
  'Open Hex Editor': '打开十六进制编辑器',
  'Show in Hex Editor': '在十六进制编辑器中显示',
  'Show Instructions in Hex Editor': '在十六进制编辑器中显示指令',
  'Show Data in Hex Editor': '在十六进制编辑器中显示数据',
  'Show Method Body in Hex Editor': '在十六进制编辑器中显示方法体',
  'Show Initial Value in Hex Editor': '在十六进制编辑器中显示初始值',
  "Hex Write 'return true' Body": '以十六进制形式写入方法体 "return true"',
  "Hex Write 'return false' Body": '以十六进制形式写入方法体 "return false"',
  'Hex Write Empty Body': '以十六进制形式写入空方法体',
  'Hex Copy Method Body': '以十六进制形式复制方法体',
  'Hex Paste Method Body': '以十六进制形式粘贴方法体',
  'Sort Table': '将表排序',
  'Sort Selection': '排序选区',
  'Go to RID...': '跳转到行 ID...',
  'Go to MD Table Row...': '转到元数据表行...',
  'Copy as Text': '复制为文本',
  'Copy': '复制',
  'Paste': '粘贴',
  'Blue Theme': '蓝色主题',
  'Light Theme': '浅色主题',
  'Dark Theme': '深色主题',
  'High Contrast': '高对比度',
  'Blue': '蓝色',
  'Dark': '深色',
  'Light': '浅色',
  'Word Wrap': '自动换行',
  'Highlight Current Line': '高亮当前行',
  'Full Screen': '全屏',
  'Collapse Tree View Nodes': '折叠树状图节点',
  'Code': '代码',
  'Hex View': '十六进制视图',
  'Hex': '十六进制',
  'Info': '信息',
  'Module Information': '模块信息',
  'System Default': '跟随系统',
  'English': 'English',
  'Simplified Chinese': '简体中文',
  'Continue': '继续',
  'Start Debugging': '开始调试',
  'Start Debugging...': '开始调试...',
  'Debug a Program': '调试程序',
  'Debug Program': '调试程序',
  'Executable': '可执行程序',
  'Arguments': '调试参数',
  'Working Directory': '工作目录',
  // The Debug Program dialog's environment box; "Environment" alone already names an Options category.
  'Environment Variables': '环境变量',
  'Break at': '中断于',
  "Don't Break": '不要中断',
  'Entry Point': '入口点',
  'Browse...': '浏览...',
  'One KEY=VALUE per line': '每行一个 KEY=VALUE',
  'OK': '确定',
  'Attach to Process...': '附加到进程...',
  'Pause': '暂停',
  'Step Into': '逐语句',
  'Step Over': '逐过程',
  'Step Out': '跳出',
  'Stop Debugging': '停止调试',
  'Stop': '停止',
  'Options...': '选项...',
  'Restore Defaults': '恢复默认值',
  'Assembly Explorer': '程序集资源管理器',
  'Output': '输出',
  'C# Interactive': 'C# 交互',
  'Search': '搜索',
  'Analyzer': '分析器',
  'Locals': '局部变量',
  'Watch': '监视',
  'Call Stack': '调用堆栈',
  'Breakpoints': '断点',
  'Module Breakpoints': '模块断点',
  'Exception Settings': '异常设置',
  'Threads': '线程',
  'Modules': '模块',
  'Autos': '自动变量',
  'Static Fields': '静态字段',
  'Processes': '进程',
  'Memory': '内存',
  'Disassembly': '反汇编',
  'Start': '开始',
  'Latest Release': '最新发布版本',
  'Report Bug': '上报错误',
  'Source Code': '源代码',
  'About dnSpy': '关于 dnSpy',
  'Workspace': '工作区',
  'Open Assembly': '打开程序集',
  'Save As': '另存为',
  'Back': '后退',
  'Forward': '前进',
  'Working': '正在处理',
  'Ready': '就绪',
  'Modified': '已修改',
  'Dismiss': '关闭提示',
  'Loading': '正在加载',
  'No assemblies loaded': '未加载程序集',
  'Collapse': '折叠',
  'Expand': '展开',
  'Main toolbar': '主工具栏',
  'Window controls': '窗口控件',
  'Minimize window': '最小化窗口',
  'Maximize window': '最大化窗口',
  'Restore window': '还原窗口',
  'Minimize': '最小化',
  'Maximize': '最大化',
  'Restore': '还原',
  'Close window': '关闭窗口',
  'Close': '关闭',
  'Search assemblies': '搜索程序集',
  'Document closed': '文档已关闭',
  'Decompiler language': '反编译语言',
  'Definition': '定义',
  'Go to definition (F12)': '转到定义 (F12)',
  'Enabled': '已启用',
  'Disabled': '已禁用',
  'Previous page': '上一页',
  'Next page': '下一页',
  'Offset': '偏移',
  'Name': '名称',
  'Value': '值',
  'Type': '类型',
  'Path': '路径',
  'Runtime': '运行时',
  'Architecture': '架构',
  // "Kind" is one word with one meaning here: dnSpy's `GP_Kind` page, the module's kind, and the kind
  // an IL operand is — 类别 for all three, which is the translation dnSpy gives the first of them.
  'Kind': '类别',
  'Entry point': '入口点',
  'Types': '类型',
  'Resources': '资源',
  'Base type': '基类型',
  'Instruction': '指令',
  'None': '无',
  'Assembly References': '程序集引用',
  'PE Headers': 'PE 头',
  'Metadata Tables': '元数据表',
  'Table': '表',
  'Rows': '行数',
  'Expression': '表达式',
  'Symbols': '符号',
  'Watch expression': '监视表达式',
  'Add watch': '添加监视',
  'Function breakpoint': '函数断点',
  'Add function breakpoint': '添加函数断点',
  'Toggle Breakpoint': '切换断点',
  'Toggle Method Breakpoint': '切换方法断点',
  'Delete All Breakpoints': '删除所有断点',
  'Bound': '已绑定',
  'Module not loaded yet.': '模块尚未加载。',
  'Not supported by this debug engine': '当前调试引擎不支持',
  'Enable All Breakpoints': '启用所有断点',
  'Disable All Breakpoints': '禁用所有断点',
  'Do you want to delete all breakpoints?': '是否删除所有的断点？',
  'Enable {name}': '启用 {name}',
  'Disable {name}': '禁用 {name}',
  'Toggle Bookmark': '切换书签',
  'Bookmark': '书签',
  'Bookmark {number}': '书签 {number}',
  'Bookmark "{name}" is in a module that is not loaded.': '书签“{name}”所在的模块尚未加载。',
  'Bookmarks Window': '书签窗口',
  'Enable Bookmark': '启用书签',
  'Disable Bookmark': '禁用书签',
  'Enable/Disable Bookmark': '启用/禁用书签',
  'Enable All Bookmarks': '启用所有书签',
  'Disable All Bookmarks': '禁用所有书签',
  'Previous Bookmark': '上一个书签',
  'Next Bookmark': '下一个书签',
  'Previous Bookmark With Same Label': '上一个同标签书签',
  'Next Bookmark With Same Label': '下一个同标签书签',
  'Previous Bookmark In Document': '文档中的上一个书签',
  'Next Bookmark In Document': '文档中的下一个书签',
  'Clear Bookmarks': '清除书签',
  'Clear All Bookmarks In Document': '清除文档中的所有书签',
  'Labels': '标签',
  'Location': '位置',
  'Module': '模块',
  'Go To': '转到',
  'Remove': '移除',
  // dnSpy.AsmEditor.Resources: Button_Edit (_Edit...), Button_Add2 (_Add...), MoveUp/MoveDown_ToolTip.
  'Edit...': '编辑(_E)...',
  'Add...': '添加(_A)...',
  'Move Up': '上移',
  'Move Down': '下移',
  // The asm-editor dialogs' shared furniture: `ConstantDlg_Constant`, `Value`, `ValueType_ToolTip`.
  // `Value` is already in the dictionary above, where a table column asked for it.
  'Constant': '常量',
  'Value type': '值类型',
  // `DataFieldVM` reports the value it could not read rather than a message of its own.
  "'{text}' is not a valid {name}": "“{text}”不是有效的 {name}",
  // The dialogs a signature is built in, which pick their parts from the same tree the explorer shows.
  '(not set)': '(未设置)',
  'Clear type': '清除类型',
  'Remove last added type': '移除最后添加的类型',
  'Add a type': '添加类型',
  'Pick a Type': '选择类型',
  'Pick a Field': '选择一个字段',
  'Pick a Method': '选择一个方法',
  'Pick a Constructor': '选择一个构造函数',
  'Pick a Generic Type': '选择泛型类型',
  'Pick an Enum Type': '选择枚举类型',
  'Pick a type': '选择类型',
  // dnSpy.AsmEditor.Resources: CustomAttributeControl and the dialog that hosts it.
  'Edit Custom Attribute': '编辑自定义特性',
  'Constructor Arguments': '构造器参数',
  'Named Arguments': '命名参数',
  'Custom Attributes': '自定义特性',
  'Constructor': '构造函数',
  'Field': '字段',
  'Property': '属性',
  'Property/Field type': '属性/字段类型',
  'The selected method cannot be used as a constructor.': '所选方法不能用作构造函数。',
  // dnSpy.AsmEditor.Resources: MethodOverrideVM / the dialog that only holds the method picker.
  'Method Overrides': '方法重写',
  'Method Override': '方法重写',
  'Edit Method Override': '编辑方法重写',
  'The selected method cannot be used as an override.': '所选方法不能用作重写。',
  // dnSpy.AsmEditor.Resources: MarshalTypeVM / MarshalTypeControl (the access keys are dropped).
  'Marshal Type': '封送类型',
  'Data': '数据',
  'VT': 'VT',
  'ElemType': '元素类型',
  'ParamNum': '参数号',
  'NumElems': '元素数量',
  'Flags': '标志',
  'GUID': 'GUID',
  'NativeType': '本机类型',
  'Cookie': 'Cookie',
  'ParamIndex': '参数索引',
  '<Not Initialized>': '<未初始化>',
  'Vector': '向量',
  'Array': '数组',
  'ByRef': '按引用',
  'Reserved': '保留',
  'A type is required': '需要一个类型',
  // dnSpy.AsmEditor.Resources: ImplMapVM / ImplMapControl. The four combo labels are the literal XAML
  // text, so only the two labels dnSpy keeps in resources are translated.
  'ImplMap': 'P/Invoke 映射',
  'A P/Invoke method needs the name of the native library it calls into.': 'P/Invoke 方法需要它所调用本机库的名称。',
  // dnSpy.AsmEditor.Resources: ParamDefVM / ParamDefControl / ParamDefDlg, and the SimpleTypeConverter
  // messages a number box can report (the access keys are dropped).
  'Sequence': '序列',
  'Sequence 0 is return parameter, sequence 1 is first parameter, etc': '序列 0 是返回参数，序列 1 是第一个参数，以此类推。',
  'In': '传入',
  'Out': '传出',
  'Lcid': 'Lcid',
  'Retval': '返回值',
  'Optional': '可选的',
  'Default value for this parameter': '参数默认值',
  'Create Parameter': '创建参数',
  'Edit Parameter': '编辑参数',
  'Parameters': '参数',
  'Main': '常规',
  'Custom Attrs': '自定义特性',
  'Only non-negative integers are allowed': '允许只非负整数',
  'The value is not an unsigned hexadecimal or decimal integer': '值不是无符号的十六进制或十进制整数',
  'Value must be between {min} and {max} (0x{maxHex}) inclusive': '值必须介于 {min} 和 {max} (0x{maxHex}) 之间',
  // dnSpy.AsmEditor.Resources: GenericParamVM / GenericParamControl / GenericParamDlg. The three
  // variance names are the fields of dnSpy's own GPVariance enum, which its EnumVM shows as they are
  // spelled there, so they are not translated. GP_Constraints and GP_GenericParamConstraints are two
  // entries with the same text upstream.
  'Create Generic Parameter': '创建泛型参数',
  'Edit Generic Parameter': '编辑泛型参数',
  'Create Generic Parameter Constraint': '创建泛型参数约束',
  'Edit Generic Parameter Constraint': '编辑泛型参数约束',
  'Generic Parameters': '泛型参数',
  'Constraints': '约束',
  'Class': '类',
  'Struct': '结构体',
  'Default ctor': '默认构造函数',
  'Allows ByRefLike': '允许 ByRefLike',
  'Variance': '方差',
  'Only used if MD header version is 1.1 (0x0101). It\'s never 1.1 so ignore Kind': '只有当元数据的头版本为 1.1 (0x0101) 时才会被使用，但它永远不可能是 1.1 所以忽略',
  // dnSpy.AsmEditor.Resources: DeclSecurityVM / DeclSecurityControl / DeclSecurityDlg and
  // SecurityAttributeVM / SecurityAttributeControl / SecurityAttributeDlg. The sixteen action names are
  // the fields of dnSpy's own SecAc enum, which its combo shows as they are spelled there, and the two
  // version labels are the fields of DeclSecVer — none of them are translated. The two combo labels are
  // this port's own: dnSpy's boxes are unlabelled.
  'Create Security Declaration': '创建安全声明',
  'Edit Security Declaration': '编辑安全声明',
  'Create Security Attribute': '创建安全特性',
  'Edit Security Attribute': '编辑安全特性',
  'Security Declarations': '安全声明',
  'Security Attributes': '安全特性',
  'XML': 'XML',
  'Action': '操作',
  'Version': '版本',
  // `CANamedArgumentVM.HasError` only reports what the value editor reports, so an empty name is legal
  // and there is no message for one.
  'null': 'null',
  '(none)': '(无)',
  'Edit Labels': '编辑标签',
  'Enable': '启用',
  'Disable': '禁用',
  'Enable Matching': '启用匹配项',
  'Disable Matching': '禁用匹配项',
  'Enable/Disable Matching Bookmarks': '启用/禁用匹配的书签',
  'Remove Matching Bookmarks': '移除匹配的书签',
  'Import Bookmarks': '导入书签',
  'Export Bookmarks': '导出书签',
  'Search bookmarks': '搜索书签',
  'Search (n: name, l: label, o: location, m: module)': '搜索 (n: 名称, l: 标签, o: 位置, m: 模块)',
  'Reset Search': '重置搜索',
  'The bookmark file could not be read.': '无法读取书签文件。',
  'Imported {count} bookmark(s).': '已导入 {count} 个书签。',
  'Exported {count} bookmark(s) to {path}.': '已导出 {count} 个书签到 {path}。',
  '{count} bookmark(s)': '{count} 个书签',
  '{count} filtered out': '{count} 个被过滤',
  'All thrown exceptions': '所有抛出的异常',
  'User-unhandled exceptions': '用户未处理的异常',
  'Attach to Process': '附加到进程',
  'Filter processes': '筛选进程',
  'Filter': '筛选',
  'Refresh': '刷新',
  'Cancel': '取消',
  'Attach': '附加',
  'Rename': '重命名',
  'Edit IL · {name}': '编辑 IL · {name}',
  'Max stack': '最大堆栈',
  'Initialize locals': '初始化局部变量',
  'Clear exception handlers': '清除异常处理程序',
  'Label': '标签',
  'Opcode': '操作码',
  'Operand': '操作数',
  'Number': '数字',
  'String': '字符串',
  'Branch': '分支',
  'Switch': '切换',
  'Local': '局部变量',
  'Argument': '参数',
  'Token': '令牌',
  'Add': '添加',
  'Apply': '应用',
  'Close About': '关闭“关于”对话框',
  'Version 1.0.0': '版本 1.0.0',
  'Cross-platform .NET assembly browser, decompiler, editor and debugger.': '跨平台 .NET 程序集浏览器、反编译器、编辑器和调试器。',
  'Licensed under GNU GPL v3.0 only.': '仅依 GNU GPL v3.0 许可证授权。',
  'Discard unsaved changes and close the workspace?': '放弃未保存的更改并关闭工作区吗？',
  'Stopped: {reason}': '已停止：{reason}',
  'starting': '正在启动',
  'ready': '就绪',
  'running': '正在运行',
  'stopped': '已停止',
  'inactive': '未启动',
  'error': '错误',
  'unknown': '未知',
  'breakpoint': '断点',
  'function breakpoint': '函数断点',
  'data breakpoint': '数据断点',
  'instruction breakpoint': '指令断点',
  'entry': '入口点',
  'step': '单步',
  'pause': '用户暂停',
  'exception': '异常',
  'Collapse {name}': '折叠 {name}',
  'Expand {name}': '展开 {name}',
  'Label {index}': '标签 {index}',
  'Opcode {index}': '操作码 {index}',
  'Operand kind {index}': '操作数类型 {index}',
  'Operand {index}': '操作数 {index}',
  'Delete instruction': '删除指令',
  'Delete instruction {index}': '删除指令 {index}',
  'Navigation failed: {message}': '导航失败：{message}',
  'Backend: {state}': '后端：{state}',
  'Backend: {state} - {message}': '后端：{state} - {message}',
  'Opened {count} module(s).': '已打开 {count} 个模块。',
  'Open failed: {message}': '打开失败：{message}',
  'Workspace closed.': '工作区已关闭。',
  'Tree load failed: {message}': '加载树失败：{message}',
  'No workspace is open.': '没有打开的工作区。',
  'Decompile failed: {message}': '反编译失败：{message}',
  'Search returned {count} result(s).': '搜索返回 {count} 个结果。',
  'Search failed: {message}': '搜索失败：{message}',
  'Analysis returned {count} reference(s).': '分析返回 {count} 个引用。',
  'Analysis failed: {message}': '分析失败：{message}',
  'Renamed {oldName} to {newName}.': '已将 {oldName} 重命名为 {newName}。',
  'Rename failed: {message}': '重命名失败：{message}',
  'Deleted {name}.': '已删除 {name}。',
  'Delete failed: {message}': '删除失败：{message}',
  'Renamed namespace {oldName} to {newName}.': '已将命名空间 {oldName} 重命名为 {newName}。',
  'Moved the types of {name} to the empty namespace.': '已将 {name} 的类型移动到空命名空间下。',
  'Namespace edit failed: {message}': '命名空间编辑失败：{message}',
  'Edit Namespace': '编辑命名空间',
  'Reset': '重置',
  'There could be code in some assembly that references this type. Are you sure you want to delete the type?': '可能有程序集中的代码引用了此类型。确定要删除该类型吗？',
  'There could be code in some assembly that references this method. Are you sure you want to delete the method?': '可能有程序集中的代码引用了此方法。确定要删除该方法吗？',
  'There could be code in some assembly that references this field. Are you sure you want to delete the field?': '可能有程序集中的代码引用了此字段。确定要删除该字段吗？',
  'Replaced resource {name}.': '已替换资源 {name}。',
  'Resource replacement failed: {message}': '替换资源失败：{message}',
  'Saved {path} ({length} bytes, SHA-256 {sha256}).': '已保存 {path}（{length} 字节，SHA-256 {sha256}）。',
  'Save failed: {message}': '保存失败：{message}',
  'Saved code to {path}.': '代码已保存到 {path}。',
  'Save code failed: {message}': '保存代码失败：{message}',
  'Updated IL body for {name}.': '已更新 {name} 的 IL 方法体。',
  'Undo completed.': '撤销完成。',
  'Undo failed: {message}': '撤销失败：{message}',
  'Redo completed.': '重做完成。',
  'Redo failed: {message}': '重做失败：{message}',
  'Started debugging {target}.': '已开始调试 {target}。',
  'Debug launch failed: {message}': '启动调试失败：{message}',
  'Attached to process {processId}.': '已附加到进程 {processId}。',
  'Debug attach failed: {message}': '附加调试失败：{message}',
  'Debugger stopped: {reason}.': '调试器已停止：{reason}。',
  'Debug target exited with code {code}.': '调试目标已退出，代码为 {code}。',
  'Debug session terminated.': '调试会话已终止。',
  'Could not refresh debugger state: {message}': '无法刷新调试器状态：{message}',
  'IL edit failed: {message}': 'IL 编辑失败：{message}',
  'Close tab': '关闭选项卡',
  'Pinned': '已固定',
  'Rename tab': '重命名选项卡',
  'Close tabset': '关闭选项卡组',
  'Active tabset': '活动选项卡组',
  'Move tabset': '移动选项卡组',
  'Move tabs (?)': '移动选项卡 (?)',
  'Move group (?)': '移动组 (?)',
  'Maximize tabset': '最大化选项卡组',
  'Restore tabset': '还原选项卡组',
  'Popout selected tab': '在新窗口中打开所选选项卡',
  'Float selected tab': '浮动所选选项卡',
  'Popout panel': '在新窗口中打开面板',
  'Drag into another layout': '拖入其他布局',
  'Dock tabs (?)': '停靠选项卡 (?)',
  'Hidden tabs': '隐藏的选项卡',
  'Resize': '调整大小',
  'Error rendering component': '组件渲染失败',
  'Retry': '重试',
  'Popout Window': '弹出窗口',
  'Pin': '固定',
  'Unpin': '取消固定',
  'Popout': '弹出',
  'Float': '浮动',
  'Pop out tabset': '弹出选项卡组',
  'Float tabset': '浮动选项卡组',
  'Overlay': '覆盖',
  'Split': '拆分',
  'Close All': '全部关闭',
  'Close to the Right': '关闭右侧选项卡',
  'Close Others': '关闭其他选项卡',
  'Add to new group': '添加到新组',
  'Add to group': '添加到组',
  'Remove from group': '从组中移除',
  'Ungroup': '取消分组',
  'Rename group': '重命名组',
  'Group color': '组颜色',
  'Tab Group, click to expand/collapse': '选项卡组，单击展开或折叠',
  'Group Name': '组名称',
  'Group color ?': '组颜色 ?',
  'Group': '组',
  'Options': '选项',
  'Prevent code from detecting the debugger': '防止代码检测调试器',
  'Enable property evaluation and other implicit function calls': '启用属性求值和其它隐式函数调用',
  'Call string-conversion function on objects in variables windows': '在变量窗口中对对象调用字符串转换方法',
  'Step over properties and operators': '逐过程执行属性和运算符',
  'Ignore Debugger.Break() and break instructions': '忽略 Debugger.Break() 和中断指令',
  'Show the Locals window when the debugger starts': '在调试器启动时显示局部变量窗口',
  'Debug files loaded from the process\' memory (uncheck to use disk files)': '调试从进程内存加载的文件 (取消选中以使用磁盘文件)',
  'Break all processes when one process breaks': '一个进程中断时则中断所有进程',
  'Enable async debugging': '启用异步调试',
  'Give focus to debugged process': '使被调试进程获得焦点',
  'Bring dnSpy to the foreground when breaking in the debugger': '当调试器中断时，为 dnSpy 设置焦点',
  'Redirect GUI applications\' console output to the Output window': '将 GUI 应用程序的控制台输出重定向到 "输出" 窗口',
  'Enable Managed Debugging Assistants (MDA)': '启用托管调试助手 (MDA)',
  'Enable Just My Code debugging support': '启用"仅我的代码"',
  'Step over code in system modules': '跳过系统模块中的代码(系统自带程序集)',
  'Only step into code located in primary module': '仅进入主模块中的代码',
  'Show raw structure of objects in variables windows': '在变量窗口中显示对象的原始结构',
  'Ignore unhandled exceptions': '忽略未处理的异常',
  'Suppress JIT optimization on module load': '在模块加载时禁用 JIT 优化',
  'System modules': '系统模块',
  'Program modules': '程序模块',
  'Hide compiler generated members': '隐藏编译器生成的成员',
  'Respect attributes that hide members': '遵守隐藏成员的特性',
  'Hide deprecated members in variables windows': '在变量窗口中隐藏已弃用的成员',
  'Sort parameters': '对参数排序',
  'Sort locals': '对局部变量排序',
  'Group parameters and locals together': '组合参数和局部变量',
  'Show compiler generated variables': '显示编译器生成的变量',
  'Show decompiler generated variables': '显示反编译器生成的变量',
  'Show raw locals': '显示原始区域变量',
  'Show return values': '显示返回值',
  'Highlight changed variables in variables windows': '在变量窗口中高亮显示更改过的变量',
  'Syntax highlight': '语法高亮',
  'Debug Engine': '调试引擎',
  'Debugger': '调试器',
  'Environment': '环境',
  'Decompiler': '反编译器',
  'Categories': '分类',
  'Search settings': '搜索设置',
  'Clear search': '清除搜索',
  'No categories match your search.': '没有符合搜索条件的分类。',
  'Select a category to view its settings.': '请选择一个分类以查看其设置。',
  'Settings shared by every debugger engine that the cross-platform backend supports.': '由跨平台后端支持的所有调试器引擎共享的设置。',
  'Cross-cutting settings that affect every part of the app.': '影响应用各个部分的全局设置。',
  'Settings that influence how .NET assemblies are decompiled into source code.': '影响 .NET 程序集如何被反编译为源代码的设置。',

  // C# Interactive: the banner's follow-up hint, the #help text and the per-submission failures.
  'Type "#help" for more information.': '键入 "#help" 获取更多信息。',
  'Resetting execution engine.': '正在重置执行引擎。',
  'Script failed: {message}': '脚本执行失败：{message}',
  'Keyboard shortcuts:': '键盘快捷键：',
  'Execute the command': '执行命令',
  'Insert a new line': '插入新行',
  'Show previous command': '显示上一条命令',
  'Show next command': '显示下一条命令',
  'REPL commands:': 'REPL 命令：',
  'Clear the script editor': '清空脚本编辑器',
  'Display the help': '显示帮助',
  'Reset the execution environment': '重置执行环境',
  'Script directives:': '脚本指令：',
  'Add a reference, either an assembly or a path to a file on disk, #r "myfile.dll"': '添加引用，可以是程序集，也可以是磁盘上的文件路径，#r "myfile.dll"',
  'Load and execute a script, #load "myscript.csx"': '加载并执行脚本，#load "myscript.csx"',

  // Compiler, Disassembler, Text Viewer, Code Editor, REPL, Output, Assembly Explorer,
  // BAML, Hex Editor, Background Image and Bookmarks settings pages.
  'Compiler': '编译器',
  'Disassembler': '反汇编器',
  'Text Viewer': '文本查看器',
  'Code Editor': '代码编辑器',
  'Output Window': '输出窗口',
  'Hex Editor': '十六进制编辑器',
  'Background Image': '背景图像',
  'Bookmarks': '书签',
  'Code Style': '代码样式',
  'Default': '默认',
  'Memory Window': '内存窗口',
  'General': '常规',
  'Scroll Bars': '滚动条',
  'Tabs': '制表符',
  'Advanced': '高级',
  'Appearance': '外观',
  'Line height': '行高',
  'Margins': '边距',
  'Zoom': '缩放',
  'Order (restart needed)': '顺序 (需要重启)',

  'Virtual space': '虚拟空间',
  'Word wrap': '自动换行',
  'Line numbers': '行号',
  'Highlight current line': '高亮当前行',
  'Highlight the current line': '高亮当前行',
  'Show line numbers': '显示行号',
  'Syntax highlight source documents': '对源文档进行语法高亮',
  'Show the minimap': '显示缩略图',
  'Show horizontal scroll bar': '显示水平滚动条',
  'Show vertical scroll bar': '显示垂直滚动条',
  'Tab size': '制表符大小',
  'Indent size': '缩进大小',
  'Convert tabs to spaces': '将制表符转换为空格',
  'Show timestamps': '显示时间戳',
  'Timestamp format': '时间戳格式',
  'Highlight references': '高亮引用',
  'Highlight related keywords': '高亮相关关键字',
  'Highlight braces': '高亮括号',
  'Show procedure line separators': '显示过程分隔线',
  'Show indent guides': '显示缩进参考线',
  'Indent guides style': '缩进参考线样式',
  'Solid lines': '实线',
  'Dashed lines (1px)': '虚线 (1px)',
  'Dashed lines (2px)': '虚线 (2px)',
  'Dashed lines (3px)': '虚线 (3px)',
  'Dashed lines (4px)': '虚线 (4px)',
  'Compress blank lines': '压缩空行',
  'Compress lines that do not have any alphanumeric characters': '压缩不含任何字母数字字符的行',
  "Don't add extra line spacing": '不添加额外的行距',
  'Selection margin': '选定内容边距',
  'Indicator margin': '指示器边距',
  'Mouse wheel zoom': '鼠标滚轮缩放',
  'Zoom control': '缩放控件',

  'Syntax': '语法',
  'Show disassembly in a new tab': '在新标签页中显示反汇编',
  'Show instruction address': '显示指令地址',
  'Show instruction bytes': '显示指令字节',
  'Show IL code': '显示 IL 代码',
  'Show decompiled code': '显示反编译的代码',
  'Add an empty line between blocks': '在块之间添加空行',
  'Add labels': '添加标签',
  'Upper case prefixes': '前缀大写',
  'Upper case mnemonics': '助记符大写',
  'Upper case registers': '寄存器大写',
  'Upper case keywords': '关键字大写',
  'Upper case hex numbers': '十六进制数字大写',
  'Upper case everything': '全部大写',
  'Space after operand separator': '操作数分隔符后的空格',
  'Space after memory operand brackets': '内存操作数方括号后的空格',
  "Space between '+'": "'+' 之间的空格",
  "Space between '*'": "'*' 之间的空格",
  'Show scale before index register': '在索引寄存器之前显示比例',
  'Always show the scale value': '始终显示比例值',
  'Always show segment registers': '始终显示段寄存器',
  'Show zero displacements': '显示零位移',
  'Add leading zeroes': '添加前导零',
  'Add leading zeroes (branches)': '添加前导零 (分支)',
  'Show small numbers in decimal': '以十进制显示小数字',
  "Add leading '0' to hex numbers if needed": '根据需要为十六进制数字添加前导 "0"',
  'Signed numbers': '有符号数字',
  'Signed displacements': '有符号位移',
  'Always show size of memory operands': '始终显示内存操作数的大小',
  'RIP-relative addresses': 'RIP 相对地址',
  'Show branch size': '显示分支大小',
  'Pseudo instructions': '伪指令',
  'Show symbol address': '显示符号地址',
  'Hex numbers': '十六进制数字',
  'Space after memory operand comma': '内存操作数逗号后的空格',
  'Naked registers': '裸寄存器',
  'Always show mnemonic size suffix': '始终显示助记符大小后缀',
  'Operand column': '操作数列',
  'Hex prefix': '十六进制前缀',
  'Hex suffix': '十六进制后缀',
  'Digit separator': '数字分隔符',

  'Conditional compilation symbols': '条件编译符号',
  'Optimize code': '优化代码',
  'Check for arithmetic overflow/underflow': '检查算术溢出/下溢',
  'Allow unsafe code': '允许不安全代码',
  'Option explicit': 'Option Explicit',
  'Option infer': 'Option Infer',
  'Option strict': 'Option Strict',
  'Option compare: binary': 'Option Compare: Binary',
  'Embed Visual Basic runtime': '嵌入 Visual Basic 运行时',

  'Dragged items filter': '拖放项筛选器',
  'All': '全部',
  'All supported': '所有支持的项',
  '.NET only': '仅 .NET',
  'Show metadata tokens': '显示元数据令牌',
  'Show assembly version': '显示程序集版本',
  'Show assembly public key token': '显示程序集公钥令牌',
  'Single-click expands nodes': '单击展开节点',
  'Nested Types': '嵌套类型',
  'Fields': '字段',
  'Events': '事件',
  'Properties': '属性',
  'Methods': '方法',

  'One attribute per line': '每行一个特性',
  'Use tabs': '使用制表符',
  'Disassemble BAML': '反汇编 BAML',

  'Highlight current value': '高亮当前值',
  'Highlight structure under mouse cursor': '高亮鼠标光标下的结构',
  'Lower case hex (values)': '十六进制小写 (值)',
  'Lower case hex (offset)': '十六进制小写 (偏移)',
  'Colorize the text': '为文本着色',
  'Group size': '组大小',
  'Encoding': '编码',
  'UTF-16 (Big Endian)': 'UTF-16 (大端序)',
  'Western European (ISO)': '西欧 (ISO)',
  'Show column line separators': '显示列分隔线',

  'Add paths to images and image folders, one path per line:': '添加图像和图像文件夹的路径，每行一个路径：',
  'Placement': '位置',
  'Top Left': '左上',
  'Top Right': '右上',
  'Bottom Left': '左下',
  'Bottom Right': '右下',
  'Top': '上',
  'Left': '左',
  'Right': '右',
  'Bottom': '下',
  'Center': '居中',
  'Opacity': '不透明度',
  'Stretch': '拉伸',
  'Fill': '填充',
  'Uniform': '均匀',
  'UniformToFill': '均匀填充',
  'Direction': '方向',
  'Both': '双向',
  'Up Only': '仅放大',
  'Down Only': '仅缩小',
  'Interval': '间隔',
  'Zoom %': '缩放 %',
  'Random Image': '随机图像',
  'Show Images': '显示图像',
  'Horizontal Offset': '水平偏移',
  'Vertical Offset': '垂直偏移',
  'Left Margin %': '左边距 %',
  'Right Margin %': '右边距 %',
  'Top Margin %': '上边距 %',
  'Bottom Margin %': '下边距 %',
  'Max Width': '最大宽度',
  'Max Height': '最大高度',

  'Theme': '主题',


  'App-wide behaviour such as the colour theme, restart handling and update checks.': '包括色彩主题、重启处理与更新检查等全局行为。',
  'The font and size used by the text editor.': '文本编辑器使用的字体和字号。',
  'Font': '字体',
  'Size': '大小',
  'Allow more than one instance (restart required)': '允许多个实例 (需要重启)',
  "Decompile a member's enclosing class instead of the class member": '反编译成员所在的类，而不是该成员',
  'Restore tabs at startup': '启动时还原标签页',
  'Use memory mapped I/O': '使用内存映射 I/O',
  'Check for updates on startup': '启动时检查更新',
  'Decompilation order': '反编译顺序',
  'Decompile anonymous methods/lambdas': '反编译匿名方法/Lambda',
  'Decompile enumerators (yield return)': '反编译枚举器 (yield return)',
  'Decompile async methods (async/await)': '反编译异步方法 (async/await)',
  'Decompile query expressions': '反编译查询表达式',
  'Decompile expression trees': '反编译表达式树',
  'Use variable names from debug symbols, if available': '使用调试符号中的变量名 (如果有)',
  'Add namespaces to all types': '为所有类型添加命名空间',
  'Add a namespace to types with the same name': '为同名的类型添加命名空间',
  'Show XML documentation in decompiled code': '在反编译的代码中显示 XML 文档',
  'Remove empty default constructors': '移除空的默认构造函数',
  'Show tokens, RVAs and file offsets': '显示令牌、RVA 和文件偏移',
  'Sort methods, fields, properties, events and types': '对方法、字段、属性、事件和类型排序',
  'Show hidden compiler generated types and methods': '显示隐藏的编译器生成的类型和方法',
  "Place 'System' directives first when sorting usings": '排序 using 时优先放置 "System" 指令',
  'Sort custom attributes': '对自定义特性排序',
  'Order members in source code order': '按源代码顺序排列成员',
  'Show one custom attribute per line': '每行显示一个自定义特性',
  'Allow field initializers': '允许字段初始值设定项',
  "Add 'internal' modifier to types": '为类型添加 "internal" 修饰符',
  "Add 'private' modifier to type members": '为类型成员添加 "private" 修饰符',
  'Hexadecimal numbers': '十六进制数字',
  'Decompile calli to invocation expression': '将 calli 反编译为调用表达式',
  'Insert parentheses for readability': '为便于阅读插入括号',
  'Show IL instruction bytes': '显示 IL 指令字节',
  'Show IL opcode comments': '显示 IL 操作码注释',
  'Show line numbers and filenames if available': '显示行号和文件名 (如果有)',

  // The type/member options windows and the controls they are built from (dnSpy.AsmEditor).
  //
  // Every other string on those pages comes from an enum, and EnumVM prints those through
  // Enum.GetName: Abstract, Sealed, Public, Value0..3, Demand, IL, Managed, SpecialName, V1/V2,
  // Covariant and the rest are spelled the same in both languages and so are absent here. The XAML
  // literals are absent for the same reason — 'Semantics' and 'Custom' on the type window's Main
  // page, and ImplMapControl's 'CharSet' / 'ThrowOn...' / 'CallConv'.
  'Base Type': '基类型',
  'Generic Params': '泛型参数',
  'Interfaces': '接口',
  'Sec Decls': '安全性说明',
  // dnSpy gives the two windows a resource each, so its method tab reads 方法签名 (MethodSignatureTab)
  // where its property tab reads 签名 (Property_Signature); the port passes one English label to both.
  'Signature': '签名',
  'Params': '参数',
  'Overrides': '重写',
  'Other Methods': '其它方法',
  'Custom Attribute': '自定义特性',
  'Method': '方法',
  'Namespace': '命名空间',
  'Access': '访问',
  'Initial Value': '初始值',
  'Delete': '删除',
  'Clear': '清除',
  'Invoke...': '调用...',
  'Remove...': '移除...',
  'Set to null': '设置为 null',
  'Default value for this field': '字段默认值',
  'Default value for this property': '属性的默认值',

  // MethodSigCreatorControl / PropertySigEditor.
  'Return Type': '返回类型',
  'Calling Conv': '调用约定',
  '# Generics': '# 泛型参数计数',
  'Method Parameter Types': '方法参数类型',
  'Method VarArg Parameter Types': '方法参数类型',

  // TypeSigCreatorControl — captions first, then the tooltips that spell each button out.
  'SZ Array': 'SZ 数组',
  'Pointer': '指针',
  'Var': '变量',
  'MVar': 'M 变量',
  'FnPtr': '函数指针',
  'GenericInst': '泛型实例',
  'CModReqd': 'C 修饰符依赖',
  'CModOpt': 'C 修饰符可选',
  'Multidimensional Array': '多维数组',
  'Rank': '维度',
  'Sizes': '长度',
  'Lower Bounds': '下标',
  'Add a type generic variable': '添加泛型变量',
  'Add a method generic variable': '添加一个方法的泛型变量',
  'Add a generic instance type': '添加一个泛型实例类型',
  'Add a function pointer': '添加函数指针',
  'Add a required C modifier': '添加依赖的 C 修饰符',
  'Add an optional C modifier': '添加可选的 C 修饰符',
  'Convert type to a pointer': '转换类型为指针',
  'Convert type to a by-reference': '将类型转换为引用',
  'Convert type to a single-dimension, zero lower-bound array': '将类型转换为一维零下限数组',
  'Convert type to a multidimensional array': '将类型转换为一个多维数组',
  'Turn it into a pinned variable': '将其更改为固定变量',
  'Type/method generic variable number': '类型/方法泛型变量数',
  'Comma separated list of array sizes (unsigned integers)': '以逗号分隔的数组长度 (无符号整数)',
  'Comma separated list of array lower bounds (signed integers)': '逗号分隔的数组下标列表 (有符号整数)',

  // Messages the port writes itself: dnSpy has no resource for these, so they are translated here
  // rather than quoted from a resx.
  'Type argument {number}': '类型参数 {number}',
  '{name} is not a generic type': '{name} 不是泛型类型',
  'The selected method cannot be used as an accessor.': '所选方法不能用作访问器。',
  'The item cannot be edited.': '该项无法编辑。',
  'Loading...': '加载中...',
  'Stopped here': '停在此处',
  'Enter runs the submission, Shift+Enter adds a line.': 'Enter 运行提交，Shift+Enter 换行。',
}

function resolveSystemLocale(): UiLocale {
  const locales = typeof navigator === 'undefined' ? [] : navigator.languages?.length ? navigator.languages : [navigator.language]
  return locales.some((locale) => locale.toLowerCase().startsWith('zh')) ? 'zh-CN' : 'en'
}

let activeLocale: UiLocale = resolveSystemLocale()

const resolveLocale = (language: LanguagePreference): UiLocale => language === 'system' ? resolveSystemLocale() : language

export const translate = (message: string, values: TranslationValues = {}): string => {
  const template = activeLocale === 'zh-CN' ? zhCN[message] ?? message : message
  return template.replace(/\{(\w+)\}/g, (placeholder, name: string) => String(values[name] ?? placeholder))
}

export const getActiveLocale = (): UiLocale => activeLocale

const loadLanguage = (): LanguagePreference => {
  const saved = localStorage.getItem('dnspy.language')
  return saved === 'en' || saved === 'zh-CN' || saved === 'system' ? saved : 'system'
}

interface LanguageContextValue {
  language: LanguagePreference
  locale: UiLocale
  setLanguage(language: LanguagePreference): void
  t: typeof translate
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'system',
  locale: activeLocale,
  setLanguage: () => undefined,
  t: translate,
})

export const LanguageProvider = ({ children, initialLanguage }: React.PropsWithChildren<{ initialLanguage?: LanguagePreference }>): React.JSX.Element => {
  const [language, setLanguageState] = useState<LanguagePreference>(() => initialLanguage ?? loadLanguage())
  const locale = resolveLocale(language)
  activeLocale = locale

  useEffect(() => {
    document.documentElement.lang = locale
    document.documentElement.dataset.locale = locale
    if (initialLanguage === undefined)
      localStorage.setItem('dnspy.language', language)
    void window.dnSpy?.setLocale?.(locale)
  }, [initialLanguage, language, locale])

  const setLanguage = useCallback((nextLanguage: LanguagePreference) => setLanguageState(nextLanguage), [])
  const context = useMemo<LanguageContextValue>(() => ({ language, locale, setLanguage, t: translate }), [language, locale, setLanguage])
  return <LanguageContext.Provider value={context}>{children}</LanguageContext.Provider>
}

export const useLanguage = (): LanguageContextValue => useContext(LanguageContext)
